### ISSUE TITLE
upgrade to eslint v4

### ISSUE THREAD

**Issue by hans-lizihan** [AfterShip/eslint-config-aftership#13]
# 4.x changes ship list

## Engine

- [x] support node >= 6 only (npm >= 3)

## Dependencies

- [x] drop unnecessary `dependencies` and `peerDenpendencies` like `eslint-plugin-react`, add them as `optionalDependencies`
- [x] bump up version of eslint as `4.1.1`
- [x] add `eslint-import-resolver-webpack`, `eslint-plugin-vue` as optionalDependency

## Features

- [x] better support vuejs rules using `eslint-plugin-vue`
- [x] support no framework generic frontend config as `aftership/frontend`

## Docs
- [x] v3 to v4 [upgrade guide](https://github.com/AfterShip/eslint-config-aftership/blob/4.x/upgrade_guides/v3tov4.md)
- [x] update `why-we-chose-those-rules`
- [x] update readme.md to indicate how to use in react projects
- [x] update readme.md to indicate how to use in vue projects

### Errors:

- [x] [no-else-return](http://eslint.org/docs/rules/no-else-return): `'error'`
- [x] [no-loop-func](http://eslint.org/docs/rules/no-loop-func): `'error'`
- [x] [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars): `['error', {vars: 'all', args: 'after-used', ignoreRestSiblings: true}]`
- [x] [no-throw-literal](http://eslint.org/docs/rules/no-throw-literal): `'error'`
- [x] [no-path-concat](http://eslint.org/docs/rules/no-path-concat): `'error'`
- [x] [indent](http://eslint.org/docs/rules/indent): `<default as eslint default>`
- [x] [no-lonely-if](http://eslint.org/docs/rules/no-lonely-if): `'error'`
- [x] [prefer-const](http://eslint.org/docs/rules/prefer-const): `'error'`
- [x] [prefer-spread](http://eslint.org/docs/rules/prefer-spread): `'error'`
- [x] [prefer-rest-params](http://eslint.org/docs/rules/prefer-rest-params): `'error'`
- [x] [react/forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md): `['error', {forbid: ['any', 'array']}]`
- [x] [react/jsx-no-bind](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md): `'react/jsx-no-bind': ['error', {ignoreRefs: true, allowArrowFunctions: true, allowBind: false}]`
- [x] [react/require-default-pros](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md): `'error'`
- [x] [vue](https://github.com/vuejs/eslint-plugin-vue): `<enabled all rules there>`

### Warnings:

- [x] [max-params](http://eslint.org/docs/rules/max-params): `['warning', 4]`
- [x] ~~[max-statements](http://eslint.org/docs/rules/max-statements): `['warning', 10]`~~
- [x] [max-lines](http://eslint.org/docs/rules/max-lines): `['warning', {max: 400, skipBlankLines: true, skipComments: true}]`
- [x] [prefer-destructing](http://eslint.org/docs/rules/prefer-destructing): `['warning', {array: true, 		object: true}, {enforceForRenamedProperties: false}]`
- [x] [return-yield](http://eslint.org/docs/rules/return-yield): `'warning'`
- [x] [react/no-danger](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md): `'warn'`

**Comment by teddychan** [comment]
What is the meaning of the "checked" item?

It means we will ship it?

**Comment by hans-lizihan** [comment]
@teddychan check means the breaking changes I have done it in the v4 branch. In case there are some rules to be drop, I'll strkethrough them.
