### ISSUE TITLE
typo on the topic tag

### ISSUE THREAD

**Issue by foray1010** [AfterShip/eslint-config-aftership#15]
it should be `javascript` instead of `jaavscript`

**Comment by hans-lizihan** [comment]
?? https://github.com/AfterShip/eslint-config-aftership/search?q=jaavscript

**Comment by foray1010** [comment]
I mean this topic tag

<img width="401" alt="screen shot 2018-03-27 at 12 54 25 pm" src="https://user-images.githubusercontent.com/3212221/37947503-05aa35a0-31be-11e8-9d1e-2b52059b8e74.png">

**Comment by aobo-y** [comment]
@foray1010 there r a lot of such projects
https://github.com/topics/jaavscript
